/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testgenericdao;

import com.michael.framework.Column;
import com.michael.framework.Id;
import com.michael.framework.JoinColumn;
import com.michael.framework.ManyToOne;
import com.michael.framework.Table;
import java.util.Date;

/**
 *
 * @author michael
 */
@Table(name="ActeurDansFilm")
public class ActeurDansFilm {
    @Id(autoGenerated=true)
    private Integer id;
    private String nom;
    @Column(name="date_mort")
    private Date dateMort;
    @Column(name="date_naissance")
    private Date dateNaissance;

    @Override
    public String toString() {
        String display = "{\n";
        display += "\tid: "+this.id+"\n";
        display += "\tnom: "+this.nom+"\n";
        display += "\tdateMort: "+this.dateMort+"\n";
        display += "\tdateNaissance: "+this.dateNaissance+"\n";
        display += "}";
        return display;
    }

    public Date getDateMort() {
        return dateMort;
    }

    public Date getDateNaissance() {
        return dateNaissance;
    }

    @ManyToOne
    @JoinColumn(name="id_film")
    private Film film;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNom() {
        return nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    public Film getFilm() {
        return film;
    }

    public void setFilm(Film film) {
        this.film = film;
    }
}
