/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testgenericdao;

import com.michael.framework.Column;
import com.michael.framework.Id;
import com.michael.framework.ManyToMany;
import java.util.Date;
import java.util.List;

/**
 *
 * @author michael
 */
public class Acteur {
    @Id(autoGenerated=true)
    private Integer id;
    private String nom;
    @Column(name="date_mort")
    private Date dateMort;
    @Column(name="date_naissance")
    private Date dateNaissance;
    
    @ManyToMany(joinTable="acteur_film", joinColumn="id_acteur", inverseJoinColumn="id_film")
    private List<Film> films;

    @Override
    public String toString() {
        String display = "{\n";
        display += "\tid: "+this.id+"\n";
        display += "\tnom: "+this.nom+"\n";
        display += "\tdateMort: "+this.dateMort+"\n";
        display += "\tdateNaissance: "+this.dateNaissance+"\n";
        display += "}";
        return display;
    }

    public List<Film> getFilms() {
        return films;
    }

    public void setFilms(List<Film> films) {
        this.films = films;
    }

    public Date getDateMort() {
        return dateMort;
    }

    public Date getDateNaissance() {
        return dateNaissance;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNom() {
        return nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    public void setDateMort(Date dateMort) {
        this.dateMort = dateMort;
    }

    public void setDateNaissance(Date dateNaissance) {
        this.dateNaissance = dateNaissance;
    }
}
