/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testgenericdao;

import com.michael.framework.Id;
import com.michael.framework.OneToMany;
import java.util.List;

/**
 *
 * @author michael
 */
public class Realisateur {
    @Id(autoGenerated=true)
    private int id;
    private String nom;

    public void setId(int id) {
        this.id = id;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }
    
    @OneToMany(mappedBy="realisateur")
    private List<Film> films;

    public int getId() {
        return id;
    }

    public String getNom() {
        return nom;
    }

    public List<Film> getFilms() {
        return films;
    }

    public void setFilms(List<Film> films) {
        this.films = films;
    }
}
